apiVersion: v2
name: preprocessing-service-cleaner
description: A Helm chart for deploying the Gravitate Health Preprocessing Service - cleanups and optimizes FHIR ePI bundles
type: application
version: 0.2.1
appVersion: "0.2.1"
keywords:
  - fhir
  - epi
  - preprocessing
  - gravitate-health
maintainers:
  - name: Gravitate Health Team
    url: https://github.com/Gravitate-Health
sources:
  - https://github.com/Gravitate-Health/preprocessing-service-cleaner
